### ISSUE TITLE
Error When Running Examples: no such dorectory "/dev/ttyS0"

### ISSUE THREAD

**Issue by Nulled-Out** [sbcshop/Pitalk_4G_HAT_Software#1]
When trying to run the text message example I get "could not open port /dev/ttyS0/ [Error 2]

Tried pressing the button and holding it too, the light is on but no difference 

On a Rpi4B (with Linux Distro) with the Pi 4G Hat in GPIO pins

**Comment by FOSS-Archives** [comment]
Would genuinely appreciate any help that could be provided here
